### ISSUE TITLE
关于“我的频道”以外的频道点击事件

### ISSUE THREAD

**Issue by Chen-keeplearn** [chengzhicao/ChannelView#10]
请问大佬，是否有设置频道编辑的方法？需求是这样的：我点击编辑，然后才能对频道进行，添加和删除，不编辑，就是一个普通的点击事件

**Comment by Chen-keeplearn** [comment]
![1561342129(1)](https://user-images.githubusercontent.com/23089663/59986284-b93c1b00-9668-11e9-9fcd-fa31e35f3e68.jpg)
在源码的基础上，就改了这个，应该可以吧

**Comment by chengzhicao** [comment]
可以
