### ISSUE TITLE
资源文件冲突

### ISSUE THREAD

**Issue by xinshengBoy** [chengzhicao/ChannelView#11]
![QQ截图20190710110940](https://user-images.githubusercontent.com/16789055/60937549-6e2a3500-a303-11e9-9277-750131659fed.png)
未做任何操作，也没有更改gradle的版本之类的，按照readme里面的引入一运行就报错

**Comment by chengzhicao** [comment]
compileSdkVersion、targetSdkVersion是多少

**Comment by xinshengBoy** [comment]
android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.yks.simpledemo2"
        minSdkVersion 19
        targetSdkVersion 27
        versionCode 3
        versionName "1.0.3"
    }

**Comment by chengzhicao** [comment]
改成28试试

**Comment by xinshengBoy** [comment]
可以了嘿，为啥前面试了那么多次都没用，奇了怪了。另外这个字体大小可以调整么，还有那个叉叉感觉太小了

**Comment by chengzhicao** [comment]
可以的
