### ISSUE TITLE
视图状态有误bug

### ISSUE THREAD

**Issue by RealMoMo** [chengzhicao/ChannelView#2]
长按拖拽完成后，有些item仍显示删除icon

**Comment by chengzhicao** [comment]
你好，能截张图吗

**Comment by W1850461829** [comment]
具体怎么复现也没找到规律，
![Uploading image.png…]()
@chenglove1201

**Comment by W1850461829** [comment]
![wechatimg1](https://user-images.githubusercontent.com/20178536/48388592-df91f380-e734-11e8-899a-274a528219e1.jpeg)

**Comment by chengzhicao** [comment]
已解决视图bug
