### ISSUE TITLE
删除频道有问题

### ISSUE THREAD

**Issue by liuqiangdd** [chengzhicao/ChannelView#6]
小米4手机，删除频道经常出错，点击好多下都删除不了

**Comment by liuqiangdd** [comment]
I/jfiowejoigwieg: down
03-25 15:09:24.368 30795-30795/com.nmpaic.hzp I/jfiowejoigwieg: 要执行了
03-25 15:09:24.373 30795-32250/com.nmpaic.hzp I/jfiowejoigwieg: 正在执行
03-25 15:09:24.440 30795-32250/com.nmpaic.hzp I/jfiowejoigwieg: 有背景了
03-25 15:09:24.453 30795-30795/com.nmpaic.hzp I/jfiowejoigwieg: up...cancel
03-25 15:09:24.453 30795-30795/com.nmpaic.hzp I/jfiowejoigwieg: 恢复
03-25 15:09:24.562 30795-30795/com.nmpaic.hzp I/jfiowejoigwieg: down
03-25 15:09:24.562 30795-30795/com.nmpaic.hzp I/jfiowejoigwieg: 要执行了
03-25 15:09:24.564 30795-32251/com.nmpaic.hzp I/jfiowejoigwieg: 正在执行
03-25 15:09:24.616 30795-30795/com.nmpaic.hzp I/jfiowejoigwieg: up...cancel
03-25 15:09:24.617 30795-32251/com.nmpaic.hzp I/jfiowejoigwieg: 取消了
03-25 15:09:24.617 30795-32251/com.nmpaic.hzp W/System.err: java.lang.InterruptedException
03-25 15:09:24.618 30795-32251/com.nmpaic.hzp W/System.err:     at java.lang.Thread.sleep(Native Method)
03-25 15:09:24.618 30795-32251/com.nmpaic.hzp W/System.err:     at java.lang.Thread.sleep(Thread.java:1031)
03-25 15:09:24.618 30795-32251/com.nmpaic.hzp W/System.err:     at java.lang.Thread.sleep(Thread.java:985)
03-25 15:09:24.618 30795-32251/com.nmpaic.hzp W/System.err:     at com.cheng.channel.ChannelView$ChannelLayout$1.run(ChannelView.java:1037)

**Comment by chengzhicao** [comment]
别的机型呢，直接添加的依赖还是下载的代码

**Comment by chengzhicao** [comment]
已修复
